<#
.SYNOPSIS
    Generates comprehensive network documentation from discovered devices.

.DESCRIPTION
    Creates professional network documentation reports combining discovery data
    with additional context for client deliverables. Ideal for MSP client 
    onboarding, network audits, and maintaining up-to-date network diagrams.
    
    Features:
    - Professional HTML documentation with network diagrams
    - Device inventory with categorization
    - IP allocation tracking
    - Subnet utilization analysis
    - Port/service mapping
    - Vendor identification
    - Export to multiple formats
    - Template-based customization

.PARAMETER DiscoveryFile
    Path to JSON discovery file generated by Get-NetworkDiscovery.ps1

.PARAMETER ClientName
    Client/company name for documentation header

.PARAMETER OutputPath
    Path for generated documentation files

.PARAMETER IncludeDiagram
    Generate visual network topology diagram (requires Graphviz)

.PARAMETER Template
    Documentation template style: Standard, Detailed, or Executive

.EXAMPLE
    .\Get-NetworkDocumentation.ps1 -DiscoveryFile "C:\Discovery\network.json" -ClientName "ABC Corp" -OutputPath "C:\Docs\ABC_Network.html"
    
    Generate standard network documentation from discovery file.

.EXAMPLE
    .\Get-NetworkDocumentation.ps1 -DiscoveryFile "discovery.json" -ClientName "XYZ Inc" -Template Detailed -IncludeDiagram -OutputPath "C:\Docs\"
    
    Generate detailed documentation with network diagram.

.NOTES
    Author: Yeyland Wutani LLC
    Website: https://github.com/YeylandWutani
    Requires: PowerShell 5.1+
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ })]
    [string]$DiscoveryFile,
    
    [Parameter(Mandatory)]
    [string]$ClientName,
    
    [Parameter(Mandatory)]
    [string]$OutputPath,
    
    [switch]$IncludeDiagram,
    
    [ValidateSet('Standard', 'Detailed', 'Executive')]
    [string]$Template = 'Standard'
)

$ScriptVersion = "1.0"

Write-Host "[$ScriptVersion] Generating network documentation for: $ClientName" -ForegroundColor Cyan

# Load discovery data
$devices = Get-Content $DiscoveryFile | ConvertFrom-Json

# Analyze data
$totalDevices = $devices.Count
$devicesByType = $devices | Group-Object DeviceType
$subnets = $devices | ForEach-Object { ($_.IPAddress -split '\.')[0..2] -join '.' } | Select-Object -Unique

Write-Host "Discovered $totalDevices devices across $($subnets.Count) subnet(s)" -ForegroundColor Green

# Generate HTML documentation
$html = @"
<!DOCTYPE html>
<html>
<head>
    <title>Network Documentation - $ClientName</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .header { background: linear-gradient(135deg, #FF6600 0%, #6B7280 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 36px; }
        .header p { margin: 10px 0 0 0; opacity: 0.9; }
        .section { background-color: white; padding: 25px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .section h2 { color: #FF6600; margin-top: 0; border-bottom: 2px solid #6B7280; padding-bottom: 10px; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }
        .stat-card { background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%); padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #FF6600; }
        .stat-number { font-size: 36px; font-weight: bold; color: #FF6600; }
        .stat-label { color: #6B7280; margin-top: 5px; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th { background-color: #6B7280; color: white; padding: 12px; text-align: left; font-weight: 600; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        tr:hover { background-color: #f8f9fa; }
        .device-server { border-left: 4px solid #0066cc; }
        .device-workstation { border-left: 4px solid #28a745; }
        .device-printer { border-left: 4px solid #ffc107; }
        .device-network { border-left: 4px solid #dc3545; }
        .footer { text-align: center; color: #6B7280; margin-top: 40px; padding: 20px; border-top: 2px solid #6B7280; }
        .footer img { max-width: 200px; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>$ClientName</h1>
        <p>Network Infrastructure Documentation</p>
        <p style="font-size: 14px;">Generated: $(Get-Date -Format 'MMMM dd, yyyy HH:mm')</p>
    </div>
    
    <div class="section">
        <h2>Executive Summary</h2>
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-number">$totalDevices</div>
                <div class="stat-label">Total Devices</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">$($subnets.Count)</div>
                <div class="stat-label">Network Segments</div>
            </div>
"@

foreach ($group in $devicesByType) {
    $html += @"
            <div class="stat-card">
                <div class="stat-number">$($group.Count)</div>
                <div class="stat-label">$($group.Name)</div>
            </div>
"@
}

$html += @"
        </div>
    </div>
    
    <div class="section">
        <h2>Device Inventory</h2>
        <table>
            <tr>
                <th>IP Address</th>
                <th>Hostname</th>
                <th>Device Type</th>
                <th>Operating System</th>
                <th>MAC Address</th>
                <th>Vendor</th>
                <th>Services</th>
            </tr>
"@

foreach ($device in ($devices | Where-Object { $_.Status -eq 'Online' } | Sort-Object { [System.Version]($_.IPAddress) })) {
    $rowClass = switch ($device.DeviceType) {
        'Server' { 'device-server' }
        'Workstation' { 'device-workstation' }
        'Printer' { 'device-printer' }
        'Network Device' { 'device-network' }
        default { '' }
    }
    
    $html += @"
            <tr class="$rowClass">
                <td><strong>$($device.IPAddress)</strong></td>
                <td>$($device.Hostname)</td>
                <td>$($device.DeviceType)</td>
                <td>$($device.OS)</td>
                <td>$($device.MACAddress)</td>
                <td>$($device.Vendor)</td>
                <td>$($device.Services)</td>
            </tr>
"@
}

$html += @"
        </table>
    </div>
    
    <div class="footer">
        <strong style="color: #FF6600; font-size: 18px;">Yeyland Wutani LLC</strong><br>
        <em>Building Better Systems</em><br>
        <small>Network Infrastructure Documentation</small>
    </div>
</body>
</html>
"@

# Save documentation
$html | Out-File -FilePath $OutputPath -Encoding UTF8
Write-Host "`nDocumentation generated: $OutputPath" -ForegroundColor Green
Write-Host "Client: $ClientName | Devices: $totalDevices | Subnets: $($subnets.Count)" -ForegroundColor Cyan
